development: &default
  db: svuchatbot
  port: 27017
  username: asakhnini256
  password : 9%3F9$i9%3FnxM
  host: cluster0.jhvduqb.mongodb.net
  retryWrites: true
  w: majority

dev : &dev
  host: localhost
  port: 27017
  readPreference: primary
  ssl: false
  db: svu_chatbot


locally:
  <<: *default
  host: mongodb
  password: Psw0rdT
  username: root
  authentication_source: admin

test:
  <<: *default
  db: svu_chatbot_test

staging: &deployed
  <<: *default
  host: 10.10.11.6
  username: root
  password: Psw0rdT
  authentication_source: admin

production:
  password: MXc3rPh247Mn97uP
  port: 27017
  host: 10.0.0.18
  username: admin
  authentication_source: admin


