@startuml packages
set namespaceSeparator none
package "src" as src {
}
package "src.root" as src.root {
}
package "src.svuchatbot_api" as src.svuchatbot_api {
}
package "src.svuchatbot_api.api" as src.svuchatbot_api.api {
}
package "src.svuchatbot_api.routes" as src.svuchatbot_api.routes {
}
package "src.svuchatbot_clustering" as src.svuchatbot_clustering {
}
package "src.svuchatbot_clustering.kmeans_based_clustering" as src.svuchatbot_clustering.kmeans_based_clustering {
}
package "src.svuchatbot_clustering.simple" as src.svuchatbot_clustering.simple {
}
package "src.svuchatbot_clustering.svm_based_cluster" as src.svuchatbot_clustering.svm_based_cluster {
}
package "src.svuchatbot_config" as src.svuchatbot_config {
}
package "src.svuchatbot_config.database" as src.svuchatbot_config.database {
}
package "src.svuchatbot_const" as src.svuchatbot_const {
}
package "src.svuchatbot_const.db" as src.svuchatbot_const.db {
}
package "src.svuchatbot_const.db.definitions" as src.svuchatbot_const.db.definitions {
}
package "src.svuchatbot_features_managment" as src.svuchatbot_features_managment {
}
package "src.svuchatbot_features_managment.features_extractor" as src.svuchatbot_features_managment.features_extractor {
}
package "src.svuchatbot_features_managment.key_words_extractor" as src.svuchatbot_features_managment.key_words_extractor {
}
package "src.svuchatbot_features_managment.morphology_based_tokens_extractor" as src.svuchatbot_features_managment.morphology_based_tokens_extractor {
}
package "src.svuchatbot_features_managment.pattern_extractor" as src.svuchatbot_features_managment.pattern_extractor {
}
package "src.svuchatbot_features_managment.root_based_bag_of_words_extractor" as src.svuchatbot_features_managment.root_based_bag_of_words_extractor {
}
package "src.svuchatbot_features_managment.simple_tokens_extractor" as src.svuchatbot_features_managment.simple_tokens_extractor {
}
package "src.svuchatbot_features_managment.tfidf_extractor" as src.svuchatbot_features_managment.tfidf_extractor {
}
package "src.svuchatbot_generator" as src.svuchatbot_generator {
}
package "src.svuchatbot_generator.intentions_generator" as src.svuchatbot_generator.intentions_generator {
}
package "src.svuchatbot_helper" as src.svuchatbot_helper {
}
package "src.svuchatbot_helper.analyser" as src.svuchatbot_helper.analyser {
}
package "src.svuchatbot_helper.clean_field" as src.svuchatbot_helper.clean_field {
}
package "src.svuchatbot_helper.cleaner" as src.svuchatbot_helper.cleaner {
}
package "src.svuchatbot_helper.data_repository" as src.svuchatbot_helper.data_repository {
}
package "src.svuchatbot_helper.drop_duplicates" as src.svuchatbot_helper.drop_duplicates {
}
package "src.svuchatbot_helper.export_entities" as src.svuchatbot_helper.export_entities {
}
package "src.svuchatbot_helper.parsing_From" as src.svuchatbot_helper.parsing_From {
}
package "src.svuchatbot_helper.parsing_To" as src.svuchatbot_helper.parsing_To {
}
package "src.svuchatbot_helper.parsing_date_from_emails" as src.svuchatbot_helper.parsing_date_from_emails {
}
package "src.svuchatbot_helper.patterns_frequency" as src.svuchatbot_helper.patterns_frequency {
}
package "src.svuchatbot_helper.read_specializations" as src.svuchatbot_helper.read_specializations {
}
package "src.svuchatbot_helper.read_stop_words" as src.svuchatbot_helper.read_stop_words {
}
package "src.svuchatbot_helper.utils" as src.svuchatbot_helper.utils {
}
package "src.svuchatbot_helper.weight_for_tokens" as src.svuchatbot_helper.weight_for_tokens {
}
package "src.svuchatbot_mogodb" as src.svuchatbot_mogodb {
}
package "src.svuchatbot_mogodb.client" as src.svuchatbot_mogodb.client {
}
package "src.svuchatbot_parsing" as src.svuchatbot_parsing {
}
package "src.svuchatbot_parsing.parse_pst" as src.svuchatbot_parsing.parse_pst {
}
package "src.svuchatbot_preprocess" as src.svuchatbot_preprocess {
}
package "src.svuchatbot_preprocess.bag_of_words_extractor" as src.svuchatbot_preprocess.bag_of_words_extractor {
}
package "src.svuchatbot_preprocess.cleand_tokens_extractor" as src.svuchatbot_preprocess.cleand_tokens_extractor {
}
package "src.svuchatbot_preprocess.entities_extractor" as src.svuchatbot_preprocess.entities_extractor {
}
package "src.svuchatbot_preprocess.extractor" as src.svuchatbot_preprocess.extractor {
}
package "src.svuchatbot_preprocess.filter" as src.svuchatbot_preprocess.filter {
}
package "src.svuchatbot_preprocess.orthographic_normalization" as src.svuchatbot_preprocess.orthographic_normalization {
}
package "src.svuchatbot_preprocess.sentiment_extractor" as src.svuchatbot_preprocess.sentiment_extractor {
}
package "src.svuchatbot_preprocess.simple_worker" as src.svuchatbot_preprocess.simple_worker {
}
package "src.svuchatbot_preprocess.special_words_extractor" as src.svuchatbot_preprocess.special_words_extractor {
}
package "src.svuchatbot_preprocess.special_words_replacment" as src.svuchatbot_preprocess.special_words_replacment {
}
package "src.svuchatbot_preprocess.tokens_extractor" as src.svuchatbot_preprocess.tokens_extractor {
}
package "src.svuchatbot_sink" as src.svuchatbot_sink {
}
package "src.svuchatbot_sink.mai_server_sink" as src.svuchatbot_sink.mai_server_sink {
}
package "src.svuchatbot_sink.pst_sink" as src.svuchatbot_sink.pst_sink {
}
package "src.svuchatbot_sink.sinker" as src.svuchatbot_sink.sinker {
}
package "src.svuchatbot_sink.telegram_sink" as src.svuchatbot_sink.telegram_sink {
}
src.root --> src.svuchatbot_clustering.kmeans_based_clustering
src.root --> src.svuchatbot_clustering.simple
src.root --> src.svuchatbot_const.db.definitions
src.root --> src.svuchatbot_features_managment.key_words_extractor
src.root --> src.svuchatbot_features_managment.pattern_extractor
src.root --> src.svuchatbot_helper.cleaner
src.root --> src.svuchatbot_helper.patterns_frequency
src.root --> src.svuchatbot_helper.utils
src.root --> src.svuchatbot_mogodb.client
src.root --> src.svuchatbot_parsing.parse_pst
src.root --> src.svuchatbot_preprocess.entities_extractor
src.root --> src.svuchatbot_preprocess.filter
src.root --> src.svuchatbot_preprocess.sentiment_extractor
src.root --> src.svuchatbot_preprocess.simple_worker
src.root --> src.svuchatbot_preprocess.special_words_extractor
src.root --> src.svuchatbot_preprocess.special_words_replacment
src.root --> src.svuchatbot_sink.pst_sink
src.svuchatbot_api.routes --> src.svuchatbot_api.api
src.svuchatbot_clustering.kmeans_based_clustering --> src.svuchatbot_const.db.definitions
src.svuchatbot_clustering.kmeans_based_clustering --> src.svuchatbot_helper.cleaner
src.svuchatbot_clustering.kmeans_based_clustering --> src.svuchatbot_helper.read_specializations
src.svuchatbot_clustering.kmeans_based_clustering --> src.svuchatbot_mogodb.client
src.svuchatbot_clustering.simple --> src.svuchatbot_mogodb.client
src.svuchatbot_config --> src.svuchatbot_config.database
src.svuchatbot_features_managment.features_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_features_managment.features_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_const.db.definitions
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_features_managment.morphology_based_tokens_extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_features_managment.simple_tokens_extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_features_managment.tfidf_extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_preprocess.bag_of_words_extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_preprocess.cleand_tokens_extractor
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_preprocess.orthographic_normalization
src.svuchatbot_features_managment.key_words_extractor --> src.svuchatbot_preprocess.special_words_extractor
src.svuchatbot_features_managment.morphology_based_tokens_extractor --> src.svuchatbot_preprocess.tokens_extractor
src.svuchatbot_features_managment.pattern_extractor --> src.svuchatbot_helper.weight_for_tokens
src.svuchatbot_features_managment.pattern_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_features_managment.pattern_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_features_managment.root_based_bag_of_words_extractor --> src.svuchatbot_features_managment.features_extractor
src.svuchatbot_features_managment.root_based_bag_of_words_extractor --> src.svuchatbot_features_managment.key_words_extractor
src.svuchatbot_features_managment.root_based_bag_of_words_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_features_managment.root_based_bag_of_words_extractor --> src.svuchatbot_preprocess.bag_of_words_extractor
src.svuchatbot_features_managment.simple_tokens_extractor --> src.svuchatbot_preprocess.tokens_extractor
src.svuchatbot_features_managment.tfidf_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_generator.intentions_generator --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.clean_field --> src.svuchatbot_const.db.definitions
src.svuchatbot_helper.clean_field --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.data_repository --> src.svuchatbot_config
src.svuchatbot_helper.data_repository --> src.svuchatbot_mogodb
src.svuchatbot_helper.drop_duplicates --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.export_entities --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.parsing_From --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.parsing_To --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.parsing_date_from_emails --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.patterns_frequency --> src.svuchatbot_mogodb.client
src.svuchatbot_helper.read_specializations --> src.svuchatbot_helper.utils
src.svuchatbot_helper.weight_for_tokens --> src.svuchatbot_mogodb.client
src.svuchatbot_mogodb --> src.svuchatbot_mogodb.client
src.svuchatbot_mogodb.client --> src.svuchatbot_config
src.svuchatbot_parsing.parse_pst --> src.svuchatbot_mogodb
src.svuchatbot_preprocess.bag_of_words_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.bag_of_words_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.cleand_tokens_extractor --> src.svuchatbot_helper.read_stop_words
src.svuchatbot_preprocess.cleand_tokens_extractor --> src.svuchatbot_helper.utils
src.svuchatbot_preprocess.cleand_tokens_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.cleand_tokens_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.entities_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.entities_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.extractor --> src.svuchatbot_mogodb
src.svuchatbot_preprocess.extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.filter --> src.svuchatbot_const.db.definitions
src.svuchatbot_preprocess.filter --> src.svuchatbot_helper.cleaner
src.svuchatbot_preprocess.filter --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.filter --> src.svuchatbot_preprocess.simple_worker
src.svuchatbot_preprocess.orthographic_normalization --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.orthographic_normalization --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.sentiment_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.sentiment_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.simple_worker --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.simple_worker --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.special_words_extractor --> src.svuchatbot_helper.read_specializations
src.svuchatbot_preprocess.special_words_extractor --> src.svuchatbot_preprocess.tokens_extractor
src.svuchatbot_preprocess.special_words_replacment --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.special_words_replacment --> src.svuchatbot_preprocess.extractor
src.svuchatbot_preprocess.tokens_extractor --> src.svuchatbot_mogodb.client
src.svuchatbot_preprocess.tokens_extractor --> src.svuchatbot_preprocess.extractor
src.svuchatbot_sink.mai_server_sink --> src.svuchatbot_mogodb.client
src.svuchatbot_sink.pst_sink --> src.svuchatbot_mogodb.client
@enduml
