class Definitions :
    #DB
    PSTDBNAME = "PST"
    PARSSEDEMAILSDBNAME = "SVU"
    TFIDFDBNAME = "TF-IDF"
    WEIGHTSDBNAME = "Weights"
    BAGOFWORDSDBNAME = "Bag-Of-Words"
    PATTERNSDBNAME = "Patterns"


    #Collections
    SENTCOLLECTIONNAME = "Sent"
    PARSSEDEMAILSCOLLECTIONNAME = "Sent-Mails-After-Parsing"
    PATTERNSCOLLECTIONNAME = "1-Gram"
    PATTERNSFREQUENCYCOLLECTIONNAME = "PatternsFrequency"
    BAGOFWORDSCOLLECTIONNAME1GRAM = "1-Gram"
    BAGOFWORDSCOLLECTIONNAME2GRAM = "2-Gram"
    BAGOFWORDSCOLLECTIONNAME3GRAM = "3-Gram"
    BAGOFWORDSCOLLECTIONNAME4GRAM = "4-Gram"
    BAGOFWORDSCOLLECTIONNAME5GRAM = "5-Gram"


    #Fields
    TOKENSFIELDNAME = "tokens"
    SIMPLETOKENSFIELDNAME = "simple-tokens"
    QUESTIONSIMPLETOKENSFIELDNAME = "question-simple-tokens"
    ANSWERSIMPLETOKENSFIELDNAME = "answer-simple-tokens"
    QUESTIONFIELDNAME = "body"
    ANSWERFIELDNAME = "replay-message"
    SPECIALWORDSFIELDNAME = "special-words"
    SPECIALWORDSFIELDNAMEFROMQUESTION = "special-words-question"
    SPECIALWORDSFIELDNAMEFROMANSWER = "special-words-answer"
